# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"HyperparamsLogger": "cb_hyperparamlogger.ipynb",
         "text2html_table": "cb_logtable.ipynb",
         "LogTableMetricsCallback": "cb_logtable.ipynb",
         "NoneReduce": "cb_mixup.ipynb",
         "reduce_loss": "cb_mixup.ipynb",
         "Mixup": "cb_mixup.ipynb",
         "MixupDict": "cb_mixup.ipynb",
         "AppConfig": "config.ipynb",
         "PathConfig": "config.ipynb",
         "TrainConfig": "config.ipynb",
         "hehe": "config.ipynb",
         "heheas": "config.ipynb",
         "AdaptiveConcatPool2d": "layers.ipynb",
         "ResnetModel": "model.ipynb",
         "listify": "utils.ipynb",
         "is_listy": "utils.ipynb",
         "camel2snake": "utils.ipynb",
         "snakify_class_name": "utils.ipynb",
         "get_default_device": "utils.ipynb",
         "unsqueeze": "utils.ipynb"}

modules = ["callback/hyperlogger.py",
           "callback/logtable.py",
           "callback/mixup.py",
           "config.py",
           "layers.py",
           "models.py",
           "utils.py"]

doc_url = "https://termanteus.github.io/isic/"

git_url = "https://github.com/termanteus/isic/tree/master/"

def custom_doc_links(name): return None
