# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"CutmixDict": "cb_cutmix.ipynb",
         "HyperparamsLogger": "cb_hyperparamlogger.ipynb",
         "text2html_table": "cb_logtable.ipynb",
         "LogTableMetricsCallback": "cb_logtable.ipynb",
         "MixupDict": "cb_mixup.ipynb",
         "AppConfig": "config.ipynb",
         "PathConfig": "config.ipynb",
         "TrainConfig": "config.ipynb",
         "hehe": "config.ipynb",
         "heheas": "config.ipynb",
         "AdaptiveConcatPool2d": "layers.ipynb",
         "MixLoss": "layers.ipynb",
         "LabelSmoothingCrossEntropy": "layers.ipynb",
         "LinBnDrop": "layers.ipynb",
         "params": "model.ipynb",
         "has_pool_type": "model.ipynb",
         "create_body": "model.ipynb",
         "ResnetModel": "model.ipynb",
         "listify": "utils.ipynb",
         "is_listy": "utils.ipynb",
         "camel2snake": "utils.ipynb",
         "snakify_class_name": "utils.ipynb",
         "get_default_device": "utils.ipynb",
         "unsqueeze": "utils.ipynb",
         "reduce_loss": "utils.ipynb",
         "NoneReduce": "utils.ipynb",
         "requires_grad": "utils.ipynb",
         "init_default": "utils.ipynb",
         "cond_init": "utils.ipynb",
         "apply_leaf": "utils.ipynb",
         "apply_init": "utils.ipynb",
         "norm_types": "utils.ipynb"}

modules = ["callback/cutmix.py",
           "callback/hyperlogger.py",
           "callback/logtable.py",
           "callback/mixup.py",
           "config.py",
           "layers.py",
           "model.py",
           "utils.py"]

doc_url = "https://termanteus.github.io/isic/"

git_url = "https://github.com/termanteus/isic/tree/master/"

def custom_doc_links(name): return None
