# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/config.ipynb (unless otherwise specified).

__all__ = ['AppConfig', 'PathConfig', 'TrainConfig', 'hehe', 'heheas']

# Cell
class AppConfig:
    SEED = 8080
    NUM_CLASSES = 7


class PathConfig:
    #     DATA_PATH = '/content/data'
    #     IMAGE_PATH = '/content/data/images'
    #     CSV_PATH = '/content/data/HAM10000_metadata.csv'

    DATA_PATH = "D:\Workspace\ML\HAM10000\data"
    IMAGE_PATH = "D:\Workspace\ML\HAM10000\data\images"
    CSV_PATH = "D:\Workspace\ML\HAM10000\data\HAM10000_metadata.csv"


class TrainConfig:
    BATCH_SIZE = 64
    EPOCHS = 100
    LR = 1e-6

# Cell
def hehe():
    print('hehe')

# Cell
def heheas():
    print('hehe')