# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/cb_freeze.ipynb (unless otherwise specified).

__all__ = ['FreezeCallback', 'UnfreezeCallback']

# Cell
from pytorch_lightning.callbacks import Callback

# Cell
class FreezeCallback(Callback):
    def on_train_start(self, trainer, pl_module):
        freeze(pl_module, trainer.optimizers[0])

class UnfreezeCallback(Callback):
    def on_train_start(self, trainer, pl_module):
        unfreeze(pl_module, trainer.optimizers[0])